#! /bin/sh

# This file is copy to ./node_modules/.bin/ after npm installation
# completed. This happened because of the instruction in
# (package.json).scripts.postInstall
#
# the shell script in ./node_modules/.bin/ can be invoked by rush-command
# or by lint-staged as specified in  <monorepo-root>/.lintstagedrc
#
# When called invoked by rush-command-line the current directory is <monorepo-root>.
# When

echo 'this is custom script in autointaller/rush-lint/node_modules/.bin/'
echo 'the execution context (pwd) is:'
pwd

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
echo "basedir: $basedir",
echo "args: $@"


